spring.application.name=spring-music

# Configurações do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_music_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
# Garante a convenção snake_case para o banco (ex: voteDate vira vote_date automaticamente)
spring.jpa.hibernate.ddl-auto=none
# 'none' porque o Flyway vai cuidar de criar e alterar as tabelas, não o Hibernate de forma automática

# Ativar o Flyway
spring.flyway.enabled=true
